name: 'Bibtex Biber Action'
author: 'Original: julianahrens, Modified: stefanbringuier'
description: 'texlive-full including biber for checking .bib file'
inputs:
  filename:
    description: 'Filename of .bib file'
    required: true
    default: 'references'
  output-directory:
    description: 'Define biber processed directory'
    required: true
    default: 'processed'
runs:
  using: 'docker'
  image: 'Dockerfile'
  args:
    - ${{ inputs.filename }}
    - ${{ inputs.output-directory }}
branding:
  icon: 'file-text'
  color: 'blue'
