name: 'Latex Biber Action'
author: 'julianahrens'
description: 'texlive-full including biber for complinig latex'
inputs:
  filename:
    description: 'Filename of .tex file'
    required: true
    default: 'main'
  output-directory:
    description: 'Define build directory'
    required: true
    default: 'out'
runs:
  using: 'docker'
  image: 'Dockerfile'
  args:
    - ${{ inputs.filename }}
    - ${{ inputs.output-directory }}
branding:
  icon: 'file-text'
  color: 'blue'
